name: learning
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  badges: ^3.0.2
  barcode_widget: ^2.0.2
  blue_thermal_printer: ^1.2.3
  bluetooth_print: ^4.3.0
  bluetooth_thermal_printer: ^0.0.6
  cached_network_image: ^3.1.0+1
  charts_flutter_new: ^0.12.0
  convert: ^3.0.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  device_info_plus: ^8.0.0
  esc_pos_utils: ^1.1.0
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_blue_plus: ^1.4.0
  flutter_cached_pdfview: ^0.4.1
  flutter_native_screenshot: ^1.1.2
  flutter_staggered_grid_view: ^0.6.2
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  google_fonts: 4.0.3
  http: ^0.13.4
  image: ^3.0.8
  image_gallery_saver: ^1.6.9
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lecle_downloads_path_provider: ^0.0.2+8
  open_file: ^3.3.2
  package_info_plus: ^3.0.2
  page_view_indicators: ^2.0.0
  path_provider: ^2.1.0
  permission_handler: ^8.1.1
  photo_view: ^0.14.0
  platform_device_id: ^1.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  rflutter_alert: ^2.0.4
  screenshot: ^2.1.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.9
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.15

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:

    - assets/rexionone.png
    - assets/icon.png
    - assets/logo.png
    - assets/noImage.png
    - assets/success.png
    - assets/error.png
    - assets/001.jpg
    - assets/mylogo.jpg
    - assets/adobe.jpg

    - assets/month00.png
    - assets/month01.png
    - assets/month02.png
    - assets/month03.png
    - assets/month04.png
    - assets/month05.png
    - assets/month06.png
    - assets/month07.png
    - assets/month08.png
    - assets/month09.png
    - assets/month10.png
    - assets/month11.png
    - assets/month12.png

    - assets/year2000.png
    - assets/year2010.png
    - assets/year2011.png
    - assets/year2012.png
    - assets/year2013.png
    - assets/year2014.png
    - assets/year2015.png
    - assets/year2016.png
    - assets/year2017.png
    - assets/year2018.png
    - assets/year2019.png
    - assets/year2020.png
    - assets/year2021.png
    - assets/year2022.png
    - assets/year2023.png
    - assets/year2024.png
    - assets/year2025.png

    - assets/home_approval.png
    - assets/home_attendance.png
    - assets/home_contact.png
    - assets/home_discussion.png
    - assets/home_meeting.png
    - assets/home_note.png
    - assets/home_notification.png
    - assets/home_todo.png
    - assets/home_project.png

    - assets/menu_login.png
    - assets/menu_logout.png
